config/routes.rb
Rails.application.routes.draw do

  resources :komodos

  match ':controller(/:action(/:id(.:format)))', :via => :all
end

app/models/komodo.rb
class Komodo < ActiveRecord::Base
    validates_presence_of :name
end

app/models/zoo.rb
class Zoo < ActiveRecord::Base
  validates_presence_of :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/komodos_controller.rb
class KomodosController < ApplicationController
  def index
    @komodos = Komodo.all
  end

  def new
    @komodo = Komodo.new
  end

  def create
    @komodo = Komodo.new(komodo_params)
    @komodo.save

    redirect_to :action => :index
  end

  def show
    @komodo = Komodo.find(params[:id])
  end

  def edit
    @komodo = Komodo.find(params[:id])
  end

  def update
    @komodo = Komodo.find(params[:id])
    @komodo.update(komodo_params)

    redirect_to :action => :show, :id => @komodo
  end

  def destroy
    @komodo = Komodo.find(params[:id])
    @komodo.destroy

    redirect_to :action => :index
  end

  private
  def komodo_params
    params.require(:komodo).permit(:name, :age)
  end

end

app/controllers/zoos_controller.rb
class ZoosController < ApplicationController
  def index
    @zoos = Zoo.all
  end

  def new
    @zoo = Zoo.new
  end

  def create
    @zoo = Zoo.new(zoo_params)
    @zoo.save

    redirect_to :action => :index
  end

  def show
    @zoo = Zoo.find(params[:id])
  end

  def edit
    @zoo = Zoo.find(params[:id])
  end

  def update
    @zoo = Zoo.find(params[:id])
    @zoo.update(zoo_params)

    redirect_to :action => :show, :id => @zoo
  end

  def destroy
    @zoo = Zoo.find(params[:id])
    @zoo.destroy

    redirect_to :action => :index
  end

  private
  def zoo_params
    params.require(:zoo).permit(:name, :age)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/komodos_helper.rb
module KomodosHelper
end

app/helpers/zoos_helper.rb
module ZoosHelper
end

app/views/komodos/edit.html.erb
<%= form_for @komodo, :url => { :controller => 'komodos', :action => 'update', :id => @komodo } do |f| %>
    <%= f.label :name, "Name" %>
    <%= f.text_field :name %>

    <%= f.label :age, "Age" %>
    <%= f.text_field :age %>

    <%= f.submit "Update" %>
<% end %>

app/views/komodos/index.html.erb
<ul>
<% @komodos.each do |komodo| %>
  <li>
    <%= komodo.name %>
      <%= link_to "Show", komodo_path(komodo) %>
      <%= link_to 'Edit', edit_komodo_path(komodo) %>
      <%= button_to 'Delete', komodo_path(komodo), :method => :delete, :data => { :confirm => "Are you sure?" } %>
    </li>
  <% end %>
  </ul>

  <%= link_to 'New Komodo', new_komodo_path %>

app/views/komodos/new.html.erb
<%= form_for @komodo, :url => { :controller => 'komodos', :action => 'create' } do |f| %>
    <%= f.label :name, "Name" %>
    <%= f.text_field :name %>

    <%= f.label :age, "Age" %>
    <%= f.text_field :age %>

    <%= f.submit "Create" %>
<% end %>

app/views/komodos/show.html.erb
<p> "Komodo Name :"</p>
<%= @komodo.name %>
<p> "Komodo Age :"</p>
<%= @komodo.age %>

<p><%= link_to 'Back to index', :controller => 'komodos', :action => 'index' %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RorZoo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/zoos/edit.html.erb
<%= form_for @zoo, :url => { :controller => 'zoos', :action => 'update', :id => @zoo } do |f| %>
    <%= f.label :name, "Name" %>
    <%= f.text_field :name %>

    <%= f.label :age, "Age" %>
    <%= f.text_field :age %>

    <%= f.submit "Update" %>
<% end %>

app/views/zoos/index.html.erb
<ul>
<% @zoos.each do |zoo| %>
  <li>
    <%= zoo.name %>
    <%= link_to 'Show', :controller => 'zoos', :action => 'show', :id => zoo %>
    <%= link_to 'Edit', :controller => 'zoos', :action => 'edit', :id => zoo %>
    <%= link_to 'Delete', :controller => 'zoos', :action => 'destroy', :id => zoo %>
  </li>
<% end %>
</ul>
<%= link_to 'New', :controller => 'zoos', :action => 'new' %>

app/views/zoos/new.html.erb
<%= form_for @zoo, :url => { :controller => 'zoos', :action => 'create' } do |f| %>
    <%= f.label :name, "Name" %>
    <%= f.text_field :name %>

    <%= f.label :age, "Age" %>
    <%= f.text_field :age %>

    <%= f.submit "Create" %>
<% end %>

app/views/zoos/show.html.erb
<%= @zoo.name %>
<%= @zoo.age %>

<p><%= link_to 'Back to index', :controller => 'zoos', :action => 'index' %></p>